from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_game(object):
    def setupUi(self, game):
        game.setObjectName("game")
        game.resize(480, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        game.setWindowIcon(icon)
        game.setStyleSheet("background-color: rgb(43,135,209)")
        self.pushButton = QtWidgets.QPushButton(parent=game)
        self.pushButton.setGeometry(QtCore.QRect(110, 120, 75, 71))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=game)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 120, 75, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=game)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 120, 75, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=game)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 200, 75, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=game)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 200, 75, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=game)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 200, 75, 71))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=game)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 280, 75, 71))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=game)
        self.pushButton_8.setGeometry(QtCore.QRect(200, 280, 75, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=game)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 280, 75, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(parent=game)
        self.label.setGeometry(QtCore.QRect(210, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170,207,237)")
        self.label.setObjectName("label")

        self.retranslateUi(game)
        QtCore.QMetaObject.connectSlotsByName(game)

    def retranslateUi(self, game):
        _translate = QtCore.QCoreApplication.translate
        game.setWindowTitle(_translate("game", "Игра запомни порядок"))
        self.pushButton.setText(_translate("game", "1"))
        self.pushButton_2.setText(_translate("game", "2"))
        self.pushButton_3.setText(_translate("game", "3"))
        self.pushButton_4.setText(_translate("game", "4"))
        self.pushButton_5.setText(_translate("game", "5"))
        self.pushButton_6.setText(_translate("game", "6"))
        self.pushButton_7.setText(_translate("game", "7"))
        self.pushButton_8.setText(_translate("game", "8"))
        self.pushButton_9.setText(_translate("game", "9"))
        self.label.setText(_translate("game", "Level: 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    game = QtWidgets.QDialog()
    ui = Ui_game()
    ui.setupUi(game)
    game.show()
    sys.exit(app.exec())
